services:
  - type: web
    name: interviewiq-backend
    env: node
    plan: free
    rootDir: 3.interviewIQ/server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 8000
      - key: CLIENT_URL
        fromService:
          type: web
          name: interviewiq-frontend
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: interviewiq-frontend
    env: static
    plan: free
    rootDir: 3.interviewIQ/client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: interviewiq-backend
          envVarKey: RENDER_EXTERNAL_URL
